version: '3.9'

services:
  grain-acceptance:
#    image: grain-acceptance
    container_name: grain-acceptance
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./build/package/dev/Dockerfile
#      dockerfile: .. /Dockerfile
#    volumes:
#      - ../.bin/:/root/
#      - ../config/:/root/config/
    ports:
      - '8080:8080'
    links:
      - postgres
        #    depends_on:
#      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-container
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1112
      - POSTGRES_DB=grain_acceptance
#      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      - ../migration/docker_postgres_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../migration/script.sql:/docker-entrypoint-initdb.d/fill_tables.sql
#      - ./migration/docker_postgres_init.sql:/docker-entrypoint-initdb.d
#      - ./migration/script.sql:/var/lib/postgresql/data/pgdata

    ports:
      - '5432:5432'
